### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by cristianespes** [johnpatrickmorgan/URLPatterns#1]
Hi,

For XCode 12.0.1:

Error message:

Failed to resolve dependencies
because URLPatterns >=0.1.9 contains incompatible tools version and root depends on URLPatterns 0.2.0..<1.0.0, version solving failed.

Can you update?

BR

**Comment by johnpatrickmorgan** [comment]
Hi, thanks for raising this issue; I've now added support for SPM. Please let me know if there are any issues.
